name: web_server
description: Web server that displays commands.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1

  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
